version: '3'

services:
 rabbitmq:
  image: rabbitmq:3-management
  ports:
   - "5672:5672"
   - "15672:15672"


 emit_log:
  build:
   context: .
   dockerfile: Dockerfile.emit_log
  ports:
   - "8081:8081"
   - "8001:8001"
  links:
   - rabbitmq


 receive:
  build:
   context: .
   dockerfile: Dockerfile.receive
  ports:
   - "8082:8082"
   - "8002:8002"
  links:
   - rabbitmq
